apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment
  labels:
    app: conv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-app
  template:
    metadata:
      labels:
        app: conv-app
    spec:
      containers:
        - name: conv-app-container
          image: antonlarichev/short-app:v1.5
          ports:
            - containerPort: 80
          env:
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: conv-app-config
                  key: VITE_DOMAIN
