apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: conv-api-container
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_EXCHANGE
              value: "test"
            - name: AMQP_HOSTNAME
              value: "rabbitmq-service"
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: rabbitmq_username
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: rabbitmq_password
          volumeMounts:
            - name: uploads
              mountPath: /opt/app/uploads
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: conv-api-pvc
