apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app-deployment
  labels:
    app: conv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-app
  template:
    metadata:
      labels:
        app: conv-app
    spec:
      containers:
        - name: conv-app-container
          image: antonlarichev/conv-app:1.2
          ports:
            - containerPort: 80
